# Generated by Django 3.2.12 on 2023-01-29 11:26

import django.contrib.postgres.fields
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NFTRewards',
            fields=[
                ('address', models.CharField(max_length=42, primary_key=True, serialize=False, validators=[django.core.validators.MinLengthValidator(42)])),
                ('ids', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=None)),
            ],
        ),
        migrations.CreateModel(
            name='NFTs',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('image', models.CharField(max_length=255)),
                ('power', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='NFTsFightData',
            fields=[
                ('address', models.CharField(max_length=42, primary_key=True, serialize=False, validators=[django.core.validators.MinLengthValidator(42)])),
                ('idF', models.IntegerField()),
                ('idS', models.IntegerField()),
                ('strikes', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=None)),
                ('firstAttacking', models.IntegerField(validators=[django.core.validators.MaxValueValidator(1), django.core.validators.MinValueValidator(0)])),
                ('message', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='NFTsInFight',
            fields=[
                ('exowner', models.CharField(max_length=42, primary_key=True, serialize=False, validators=[django.core.validators.MinLengthValidator(42)])),
                ('id', models.IntegerField()),
                ('name', models.CharField(max_length=255)),
                ('image', models.CharField(max_length=255)),
                ('power', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='NFTsOnSale',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('image', models.CharField(max_length=255)),
                ('power', models.IntegerField()),
                ('price', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Nodes',
            fields=[
                ('uri', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=255)),
                ('x', models.FloatField()),
                ('y', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Points',
            fields=[
                ('address', models.CharField(max_length=42, primary_key=True, serialize=False, validators=[django.core.validators.MinLengthValidator(42)])),
                ('point', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='WaitingShilaRequests',
            fields=[
                ('address', models.CharField(max_length=42, primary_key=True, serialize=False, validators=[django.core.validators.MinLengthValidator(42)])),
                ('point', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Wallets',
            fields=[
                ('username', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('key', models.CharField(max_length=255)),
            ],
        ),
    ]
